[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[build.environment]


[[redirects]]
  from = "/chat/*"
  to = "/chat.html"
  status = 200

  NODE_VERSION = "22"

